
package telas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import bd.dbos.Mensagem;
import bd.dbos.Usuario;
import transmissor.ClienteSocket;
import transmissor.Solicitacao;

/**
 *Janela de cadastro, junto as suas configura��es e difini��es do uso de cada bot�o.
 * @author Felipe
 */
public class JanelaCadastro extends javax.swing.JPanel {

    /**
     * Creates new form JanelaCadastro
     */
    
    // ATRIBUTOS DE JANELA CADASTRO
    private JFrame janelaNova; // ou 'fecha'
    private final String DIVISOR = ":";
    
    // CONSTRUTOR
    public JanelaCadastro(JFrame janelaNova) {
        this.janelaNova = janelaNova;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOK = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        txtNomeCadastro = new javax.swing.JLabel();
        txtEmailCadastro = new javax.swing.JLabel();
        txtSenhaCadastro = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtConfirma = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmaSenha = new javax.swing.JPasswordField();

        setName(""); // NOI18N

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancela");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        txtNomeCadastro.setText("Nome:");

        txtEmailCadastro.setText("e-Mail:");

        txtSenhaCadastro.setText("Senha:");

        txtConfirma.setText("Confirma��o:");

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCadastro)
                            .addComponent(txtEmailCadastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtNome))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSenhaCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnOK)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancela)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtConfirma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(txtNomeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaCadastro)
                    .addComponent(txtConfirma)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancela))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        txtConfirmaSenha.setText("");
        txtEmail.setText("");
        txtNome.setText("");
        txtSenha.setText("");
        
        JFrame janela = new JFrame("Login");
        JanelaLogin login = new JanelaLogin(janela);
        
        janela.add(login);
        janela.pack();
        janela.setLocationRelativeTo(login);
        janela.setVisible(true);
        this.janelaNova.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
            
        try {
			// verifica se algum campo nao foi preenchido
			if (txtEmail.getText().isEmpty() || txtNome.getText().isEmpty() || txtSenha.getText().isEmpty() || txtConfirmaSenha.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Erro! Espacos em branco, digite em todos os campos!");
			} else {
				ClienteSocket clienteSocket = ClienteSocket.getClienteSocket();
				// verifica se o campo senha eh igual ao campo de confirmacao
				if (txtSenha.getText().equals(txtConfirmaSenha.getText())) {
					//Usuario usuario = new Usuario(txtNome.getText(), txtEmail.getText(), txtSenha.getText(), "CAD");
					//Solicitacao solicitacao = new Solicitacao(usuario);
					Mensagem mensagem = new Mensagem("CAD",txtNome.getText()+DIVISOR+txtEmail.getText()+DIVISOR+txtSenha.getText());
					clienteSocket.enviaDados(mensagem);
				
					clienteSocket.waitMessagem();
					Mensagem retorno = clienteSocket.getMessagem();
					
						if (retorno.getProtocolo().equals("SUC")) {
							JOptionPane.showMessageDialog(null, "Usu�rio Cadastrado com Sucesso!");
							
				            JFrame janela = new JFrame("Login");
				            JanelaLogin login = new JanelaLogin(janela);

				            janela.add(login);
				            janela.pack();
				            janela.setLocationRelativeTo(login);
				            janela.setVisible(true);
				            this.janelaNova.dispose();

						} else {
							JOptionPane.showMessageDialog(null, "Erro! Espacos em branco, digite em todos os campos!");
						}
				} 
				else
				{
					JOptionPane.showMessageDialog(null, "Erro! As senhas digitadas n�o coincidem!");
				}
			}
		} catch (Exception erro) {
			System.err.println(erro);
		}
            
            
    }//GEN-LAST:event_btnOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel txtConfirma;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtEmailCadastro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel txtNomeCadastro;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JLabel txtSenhaCadastro;
    // End of variables declaration//GEN-END:variables
}
