/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import bd.dbos.Usuario;
import transmissor.Solicitacao;

/**
 * Janela de Login, onde reliza a validação com o banco de dados dos itens nele
 * já colocados.
 * 
 * @author melin
 */
public class JanelaLogin extends javax.swing.JPanel {

	/**
	 * Creates new form JanelaLogin
	 */
	JFrame fecha;

	public JanelaLogin(JFrame fecha) {
		this.fecha = fecha;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		btnEntrar = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		btnCadastrar = new javax.swing.JButton();
		txtEmail = new javax.swing.JTextField();
		txtEmailLogin = new javax.swing.JLabel();
		txtSenhaLogin = new javax.swing.JLabel();
		txtSenha = new javax.swing.JPasswordField();

		btnEntrar.setText("Entrar");
		btnEntrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEntrarActionPerformed(evt);
			}
		});

		btnCancelar.setText("Cancelar");
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});

		btnCadastrar.setText("Cadastrar-se");
		btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCadastrarActionPerformed(evt);
			}
		});

		txtEmailLogin.setText("e-Mail:");

		txtSenhaLogin.setText("Senha:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(20, 20, 20).addComponent(btnEntrar)
										.addGap(20, 20, 20).addComponent(btnCancelar).addGap(20, 20, 20).addComponent(
												btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addContainerGap()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtEmail).addComponent(txtSenha))))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(38, 38, 38)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnCancelar).addComponent(btnEntrar).addComponent(btnCadastrar))
						.addGap(19, 19, 19)));

		btnCancelar.getAccessibleContext().setAccessibleName("btnCancelar");
	}// </editor-fold>//GEN-END:initComponents

	private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCadastrarActionPerformed
		JFrame janelacadastro = new JFrame("Cadastro");
		JanelaCadastro cadastro = new JanelaCadastro(janelacadastro);

		janelacadastro.add(cadastro);
		janelacadastro.pack();
		janelacadastro.setLocationRelativeTo(cadastro);
		janelacadastro.setVisible(true);
		this.fecha.dispose(); // Fechando a view antiga (janela de Login)

	}// GEN-LAST:event_btnCadastrarActionPerformed

	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
		txtEmail.setText("");
		txtSenha.setText("");
	}// GEN-LAST:event_btnCancelarActionPerformed

	@SuppressWarnings("deprecation")
	private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEntrarActionPerformed
		try {

			if (txtEmail.getText().isEmpty() || txtSenha.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Erro! Espacos em branco, digite em todos os campos!");
			} else {
				Usuario usuario = new Usuario(txtEmail.getText(), txtSenha.getText(), "LOG");
				Solicitacao solicitacao = new Solicitacao(usuario);

				if (solicitacao.Enviar(usuario).equals("SUC")) {
					JOptionPane.showMessageDialog(null, "Login com sucesso!");
					
					JFrame janelaEscolherPartida = new JFrame("EscolherPartida");
					TelaEscolhePartida escolherPartida = new TelaEscolhePartida(janelaEscolherPartida);

					janelaEscolherPartida.add(escolherPartida);
					janelaEscolherPartida.pack();
					janelaEscolherPartida.setLocationRelativeTo(escolherPartida);
					janelaEscolherPartida.setVisible(true);
					this.fecha.dispose(); // Fechando a view antiga (janela de Login)
				} else {
					JOptionPane.showMessageDialog(null, "Erro! E-mail ou senha incorreto(s)!");
				}
			}

		} catch (Exception erro) {
			System.err.println(erro);
		}
	}// GEN-LAST:event_btnEntrarActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCadastrar;
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnEntrar;
	private javax.swing.JTextField txtEmail;
	private javax.swing.JLabel txtEmailLogin;
	private javax.swing.JPasswordField txtSenha;
	private javax.swing.JLabel txtSenhaLogin;
	// End of variables declaration//GEN-END:variables
}
