/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Label;
import java.awt.Font;

/**
 *
 * @author melin
 */
public class TelaPartida extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrePartida
     */
    public TelaPartida() {
    	lblValorTotal.setText("Total das Cartas:");
    	lblCartasNaMao.setText("Cartas");
    	lblCartasNaMao.setFont(new Font("Dialog", Font.BOLD, 12));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnParar = new javax.swing.JButton();
        btnComprarCarta = new javax.swing.JButton();
        lblCartaUsuario = new java.awt.Label();
        lblTotalCartas = new java.awt.Label();
        lblJogador4 = new javax.swing.JLabel();
        lblApostaJogador8 = new javax.swing.JLabel();
        lblJogador5 = new javax.swing.JLabel();
        lblApostaJogador2 = new javax.swing.JLabel();
        lblJogador6 = new javax.swing.JLabel();
        lblJogador = new javax.swing.JLabel();
        lblJogador7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblJogador8 = new javax.swing.JLabel();
        lblApostaJogador1 = new javax.swing.JLabel();
        lblApostaJogador3 = new javax.swing.JLabel();
        lblJogador1 = new javax.swing.JLabel();
        lblApostaJogador4 = new javax.swing.JLabel();
        lblApostaJogador5 = new javax.swing.JLabel();
        lblJogador2 = new javax.swing.JLabel();
        lblApostaJogador6 = new javax.swing.JLabel();
        lblJogador3 = new javax.swing.JLabel();
        lblApostaJogador7 = new javax.swing.JLabel();
        lblCartasNoBaralho = new javax.swing.JLabel();
        txtQntBaralho = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        lblMoedas = new javax.swing.JLabel();
        txtValorApostar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnParar.setText("Parar");

        btnComprarCarta.setText("Comprar Carta!");

        lblCartaUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCartaUsuario.setText("Cartas");

        lblTotalCartas.setText("Total das Cartas:");

        lblJogador4.setText("Vazio");

        lblApostaJogador8.setText("000");

        lblJogador5.setText("Vazio");

        lblApostaJogador2.setText("000");

        lblJogador6.setText("Vazio");

        lblJogador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblJogador.setText("Jogador");

        lblJogador7.setText("Vazio");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("Aposta");

        lblJogador8.setText("Vazio");

        lblApostaJogador1.setText("000");

        lblApostaJogador3.setText("000");

        lblJogador1.setText("Vazio");

        lblApostaJogador4.setText("000");

        lblApostaJogador5.setText("000");

        lblJogador2.setText("Vazio");

        lblApostaJogador6.setText("000");

        lblJogador3.setText("Vazio");

        lblApostaJogador7.setText("000");

        lblCartasNoBaralho.setText("Cartas no Baralho");

        txtQntBaralho.setText("0");

        btnSair.setText("Sair");

        lblMoedas.setText("Suas Moedas:");

        txtValorApostar.setText("0");
        
        btnApostar = new JButton();
        btnApostar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        btnApostar.setText("Apostar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnSair)
        					.addGap(23))
        				.addGroup(layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(layout.createSequentialGroup()
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(lblJogador2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblJogador1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblJogador3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblJogador4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblJogador5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblJogador6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblJogador7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblJogador8, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
        							.addComponent(lblJogador))
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(lblApostaJogador2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblApostaJogador1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblApostaJogador3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblApostaJogador4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblApostaJogador5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblApostaJogador6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblApostaJogador7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(lblApostaJogador8, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
        							.addComponent(jLabel18))
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addGroup(layout.createSequentialGroup()
        								.addGap(51)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addGroup(layout.createSequentialGroup()
        										.addPreferredGap(ComponentPlacement.RELATED)
        										.addComponent(btnComprarCarta, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE)
        										.addGap(18)
        										.addComponent(btnParar, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
        										.addGap(30)
        										.addComponent(btnApostar, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
        										.addPreferredGap(ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
        										.addComponent(txtValorApostar, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        										.addGap(28))
        									.addGroup(layout.createSequentialGroup()
        										.addGap(83)
        										.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        											.addGroup(layout.createSequentialGroup()
        												.addComponent(lblCartaUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        												.addGap(76))
        											.addComponent(lblTotalCartas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        										.addContainerGap(404, Short.MAX_VALUE))))
        							.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        								.addPreferredGap(ComponentPlacement.RELATED)
        								.addComponent(lblMoedas)
        								.addGap(41))))
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(txtQntBaralho, Alignment.LEADING)
        						.addComponent(lblCartasNoBaralho, Alignment.LEADING)))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblCartaUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(12)
        					.addComponent(lblMoedas)
        					.addGap(161)
        					.addComponent(lblTotalCartas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(23)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblJogador)
        						.addComponent(jLabel18))
        					.addGap(14)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(lblJogador1)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblJogador2)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblJogador3)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblJogador4)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblJogador5)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblJogador6)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblJogador7)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblJogador8))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(lblApostaJogador1)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblApostaJogador2)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblApostaJogador3)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblApostaJogador4)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblApostaJogador5)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblApostaJogador6)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblApostaJogador7)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblApostaJogador8)))))
        			.addGap(10)
        			.addComponent(lblCartasNoBaralho)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(txtQntBaralho, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        			.addGap(23)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnParar, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnComprarCarta, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnApostar, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtValorApostar, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        			.addComponent(btnSair)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);
        btnParar.getAccessibleContext().setAccessibleName("btnPararJogada");
        btnParar.getAccessibleContext().setAccessibleDescription("");
        btnComprarCarta.getAccessibleContext().setAccessibleName("btnComprarCarta");
        lblCartaUsuario.getAccessibleContext().setAccessibleName("lblCartas");
        lblTotalCartas.getAccessibleContext().setAccessibleName("lblValorTotalCartajogador");
        lblJogador4.getAccessibleContext().setAccessibleName("lblJogador4");
        lblApostaJogador8.getAccessibleContext().setAccessibleName("lblApostaJogador8");
        lblJogador5.getAccessibleContext().setAccessibleName("lblJogador5");
        lblApostaJogador2.getAccessibleContext().setAccessibleName("lblApostaJogador2");
        lblJogador6.getAccessibleContext().setAccessibleName("lblJogador6");
        lblJogador.getAccessibleContext().setAccessibleName("lblJogadores");
        lblJogador7.getAccessibleContext().setAccessibleName("lblJogador7");
        jLabel18.getAccessibleContext().setAccessibleName("lblAposta");
        lblJogador8.getAccessibleContext().setAccessibleName("lblJogador8");
        lblApostaJogador1.getAccessibleContext().setAccessibleName("lblApostaJogador1");
        lblApostaJogador3.getAccessibleContext().setAccessibleName("lblApostaJogador3");
        lblJogador1.getAccessibleContext().setAccessibleName("lblJogador1");
        lblApostaJogador4.getAccessibleContext().setAccessibleName("lblApostaJogador4");
        lblApostaJogador5.getAccessibleContext().setAccessibleName("lblApostaJogador5");
        lblJogador2.getAccessibleContext().setAccessibleName("lblJogador2");
        lblApostaJogador6.getAccessibleContext().setAccessibleName("lblApostaJogador6");
        lblJogador3.getAccessibleContext().setAccessibleName("lblJogador3");
        lblApostaJogador7.getAccessibleContext().setAccessibleName("lblApostaJogador7");
        lblCartasNoBaralho.getAccessibleContext().setAccessibleName("lblCartasBaralho");
        txtQntBaralho.getAccessibleContext().setAccessibleName("txtQuantidadeBaralho");
        btnSair.getAccessibleContext().setAccessibleName("btnSairPartida");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarCarta;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel lblApostaJogador1;
    private javax.swing.JLabel lblApostaJogador2;
    private javax.swing.JLabel lblApostaJogador3;
    private javax.swing.JLabel lblApostaJogador4;
    private javax.swing.JLabel lblApostaJogador5;
    private javax.swing.JLabel lblApostaJogador6;
    private javax.swing.JLabel lblApostaJogador7;
    private javax.swing.JLabel lblApostaJogador8;
    private java.awt.Label lblCartaUsuario;
    private javax.swing.JLabel lblCartasNoBaralho;
    private javax.swing.JLabel lblJogador;
    private javax.swing.JLabel lblJogador1;
    private javax.swing.JLabel lblJogador2;
    private javax.swing.JLabel lblJogador3;
    private javax.swing.JLabel lblJogador4;
    private javax.swing.JLabel lblJogador5;
    private javax.swing.JLabel lblJogador6;
    private javax.swing.JLabel lblJogador7;
    private javax.swing.JLabel lblJogador8;
    private javax.swing.JLabel lblMoedas;
    private java.awt.Label lblTotalCartas;
    private javax.swing.JTextField txtQntBaralho;
    private javax.swing.JTextField txtValorApostar;
    private JButton btnApostar;
    /**
     * @wbp.nonvisual location=264,107
     */
    private final Label lblCartasNaMao = new Label();
    /**
     * @wbp.nonvisual location=334,287
     */
    private final Label lblValorTotal = new Label();
    /**
     * @wbp.nonvisual location=695,117
     */
    private final Label qtdMoedas = new Label("New label");
}
