/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author melin
 */
public class TelaPartida extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrePartida
     */
    public TelaPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCarta1 = new java.awt.TextField();
        txtCarta2 = new java.awt.TextField();
        txtCarta3 = new java.awt.TextField();
        txtCarta4 = new java.awt.TextField();
        txtCarta5 = new java.awt.TextField();
        txtValorCarta1 = new java.awt.TextField();
        btnParar = new javax.swing.JButton();
        btnComprarCarta = new javax.swing.JButton();
        txtValorCarta2 = new java.awt.TextField();
        txtValorCarta3 = new java.awt.TextField();
        txtValorCarta4 = new java.awt.TextField();
        txtValorCarta5 = new java.awt.TextField();
        txtTotalCartas = new java.awt.TextField();
        lblCartaUsuario = new java.awt.Label();
        lblValorCarta = new java.awt.Label();
        lblTotalCartas = new java.awt.Label();
        lblJogador4 = new javax.swing.JLabel();
        lblApostaJogador8 = new javax.swing.JLabel();
        lblJogador5 = new javax.swing.JLabel();
        lblApostaJogador2 = new javax.swing.JLabel();
        lblJogador6 = new javax.swing.JLabel();
        lblJogador = new javax.swing.JLabel();
        lblJogador7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblJogador8 = new javax.swing.JLabel();
        lblApostaJogador1 = new javax.swing.JLabel();
        lblApostaJogador3 = new javax.swing.JLabel();
        lblJogador1 = new javax.swing.JLabel();
        lblApostaJogador4 = new javax.swing.JLabel();
        lblApostaJogador5 = new javax.swing.JLabel();
        lblJogador2 = new javax.swing.JLabel();
        lblApostaJogador6 = new javax.swing.JLabel();
        lblJogador3 = new javax.swing.JLabel();
        lblApostaJogador7 = new javax.swing.JLabel();
        lblCartasNoBaralho = new javax.swing.JLabel();
        txtQntBaralho = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        lblMoedas = new javax.swing.JLabel();
        txtQntMoedas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCarta1.setText("0");

        txtCarta2.setText("0");

        txtCarta3.setText("0");

        txtCarta4.setText("0");

        txtCarta5.setText("0");

        txtValorCarta1.setName(""); // NOI18N
        txtValorCarta1.setText("0");

        btnParar.setText("Parar");

        btnComprarCarta.setText("Comprar Carta!");

        txtValorCarta2.setName(""); // NOI18N
        txtValorCarta2.setText("0");

        txtValorCarta3.setName(""); // NOI18N
        txtValorCarta3.setText("0");

        txtValorCarta4.setName(""); // NOI18N
        txtValorCarta4.setText("0");

        txtValorCarta5.setName(""); // NOI18N
        txtValorCarta5.setText("0");

        txtTotalCartas.setText("0");

        lblCartaUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCartaUsuario.setText("Carta");

        lblValorCarta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValorCarta.setText("Valor");

        lblTotalCartas.setText("Total das Cartas:");

        lblJogador4.setText("Vazio");

        lblApostaJogador8.setText("000");

        lblJogador5.setText("Vazio");

        lblApostaJogador2.setText("000");

        lblJogador6.setText("Vazio");

        lblJogador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblJogador.setText("Jogador");

        lblJogador7.setText("Vazio");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("Aposta");

        lblJogador8.setText("Vazio");

        lblApostaJogador1.setText("000");

        lblApostaJogador3.setText("000");

        lblJogador1.setText("Vazio");

        lblApostaJogador4.setText("000");

        lblApostaJogador5.setText("000");

        lblJogador2.setText("Vazio");

        lblApostaJogador6.setText("000");

        lblJogador3.setText("Vazio");

        lblApostaJogador7.setText("000");

        lblCartasNoBaralho.setText("Cartas no Baralho");

        txtQntBaralho.setText("0");

        btnSair.setText("Sair");

        lblMoedas.setText("Suas Moedas:");

        txtQntMoedas.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblJogador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblApostaJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblApostaJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblApostaJogador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblApostaJogador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblApostaJogador5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblApostaJogador6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblApostaJogador7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblApostaJogador8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComprarCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtValorCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtValorCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtValorCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtValorCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtValorCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCartaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(lblValorCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTotalCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtQntBaralho, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCartasNoBaralho, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(166, 166, 166)
                        .addComponent(txtTotalCartas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtQntMoedas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMoedas, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCartaUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtValorCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(30, 30, 30))
                                                    .addComponent(txtValorCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30))
                                            .addComponent(txtValorCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30))
                                    .addComponent(txtValorCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(lblTotalCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJogador)
                            .addComponent(jLabel18))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblJogador1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblJogador2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblJogador3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblJogador4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblJogador5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblJogador6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblJogador7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblJogador8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblApostaJogador1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblApostaJogador2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblApostaJogador3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblApostaJogador4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblApostaJogador5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblApostaJogador6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblApostaJogador7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblApostaJogador8)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblCartasNoBaralho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQntBaralho, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMoedas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQntMoedas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprarCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );

        txtCarta1.getAccessibleContext().setAccessibleName("txtCarta1");
        txtCarta2.getAccessibleContext().setAccessibleName("txtCarta2");
        txtCarta3.getAccessibleContext().setAccessibleName("txtCarta3");
        txtCarta4.getAccessibleContext().setAccessibleName("txtCarta4");
        txtCarta5.getAccessibleContext().setAccessibleName("txtCarta5");
        txtValorCarta1.getAccessibleContext().setAccessibleName("txtValorCarta1");
        btnParar.getAccessibleContext().setAccessibleName("btnPararJogada");
        btnParar.getAccessibleContext().setAccessibleDescription("");
        btnComprarCarta.getAccessibleContext().setAccessibleName("btnComprarCarta");
        txtValorCarta2.getAccessibleContext().setAccessibleName("txtValorCarta2");
        txtValorCarta3.getAccessibleContext().setAccessibleName("txtValorCarta3");
        txtValorCarta4.getAccessibleContext().setAccessibleName("txtValorCarta4");
        txtValorCarta4.getAccessibleContext().setAccessibleDescription("");
        txtValorCarta5.getAccessibleContext().setAccessibleName("txtValorCarta5");
        txtTotalCartas.getAccessibleContext().setAccessibleName("txtTotalCartas");
        txtTotalCartas.getAccessibleContext().setAccessibleDescription("");
        lblCartaUsuario.getAccessibleContext().setAccessibleName("lblCartas");
        lblValorCarta.getAccessibleContext().setAccessibleName("lblValorCarta");
        lblTotalCartas.getAccessibleContext().setAccessibleName("lblValorTotalCartajogador");
        lblJogador4.getAccessibleContext().setAccessibleName("lblJogador4");
        lblApostaJogador8.getAccessibleContext().setAccessibleName("lblApostaJogador8");
        lblJogador5.getAccessibleContext().setAccessibleName("lblJogador5");
        lblApostaJogador2.getAccessibleContext().setAccessibleName("lblApostaJogador2");
        lblJogador6.getAccessibleContext().setAccessibleName("lblJogador6");
        lblJogador.getAccessibleContext().setAccessibleName("lblJogadores");
        lblJogador7.getAccessibleContext().setAccessibleName("lblJogador7");
        jLabel18.getAccessibleContext().setAccessibleName("lblAposta");
        lblJogador8.getAccessibleContext().setAccessibleName("lblJogador8");
        lblApostaJogador1.getAccessibleContext().setAccessibleName("lblApostaJogador1");
        lblApostaJogador3.getAccessibleContext().setAccessibleName("lblApostaJogador3");
        lblJogador1.getAccessibleContext().setAccessibleName("lblJogador1");
        lblApostaJogador4.getAccessibleContext().setAccessibleName("lblApostaJogador4");
        lblApostaJogador5.getAccessibleContext().setAccessibleName("lblApostaJogador5");
        lblJogador2.getAccessibleContext().setAccessibleName("lblJogador2");
        lblApostaJogador6.getAccessibleContext().setAccessibleName("lblApostaJogador6");
        lblJogador3.getAccessibleContext().setAccessibleName("lblJogador3");
        lblApostaJogador7.getAccessibleContext().setAccessibleName("lblApostaJogador7");
        lblCartasNoBaralho.getAccessibleContext().setAccessibleName("lblCartasBaralho");
        txtQntBaralho.getAccessibleContext().setAccessibleName("txtQuantidadeBaralho");
        btnSair.getAccessibleContext().setAccessibleName("btnSairPartida");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarCarta;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel lblApostaJogador1;
    private javax.swing.JLabel lblApostaJogador2;
    private javax.swing.JLabel lblApostaJogador3;
    private javax.swing.JLabel lblApostaJogador4;
    private javax.swing.JLabel lblApostaJogador5;
    private javax.swing.JLabel lblApostaJogador6;
    private javax.swing.JLabel lblApostaJogador7;
    private javax.swing.JLabel lblApostaJogador8;
    private java.awt.Label lblCartaUsuario;
    private javax.swing.JLabel lblCartasNoBaralho;
    private javax.swing.JLabel lblJogador;
    private javax.swing.JLabel lblJogador1;
    private javax.swing.JLabel lblJogador2;
    private javax.swing.JLabel lblJogador3;
    private javax.swing.JLabel lblJogador4;
    private javax.swing.JLabel lblJogador5;
    private javax.swing.JLabel lblJogador6;
    private javax.swing.JLabel lblJogador7;
    private javax.swing.JLabel lblJogador8;
    private javax.swing.JLabel lblMoedas;
    private java.awt.Label lblTotalCartas;
    private java.awt.Label lblValorCarta;
    private java.awt.TextField txtCarta1;
    private java.awt.TextField txtCarta2;
    private java.awt.TextField txtCarta3;
    private java.awt.TextField txtCarta4;
    private java.awt.TextField txtCarta5;
    private javax.swing.JTextField txtQntBaralho;
    private javax.swing.JTextField txtQntMoedas;
    private java.awt.TextField txtTotalCartas;
    private java.awt.TextField txtValorCarta1;
    private java.awt.TextField txtValorCarta2;
    private java.awt.TextField txtValorCarta3;
    private java.awt.TextField txtValorCarta4;
    private java.awt.TextField txtValorCarta5;
    // End of variables declaration//GEN-END:variables
}
