/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author melin
 */
public class TelaPrePartida extends javax.swing.JFrame {

    /**
     * Creates new form TelaPartida
     */
    public TelaPrePartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        lblStatusjogador1 = new javax.swing.JLabel();
        lblStatusjogador3 = new javax.swing.JLabel();
        lblJogador1 = new javax.swing.JLabel();
        lblStatusjogador4 = new javax.swing.JLabel();
        lblStatusjogador5 = new javax.swing.JLabel();
        lblJogador2 = new javax.swing.JLabel();
        lblStatusjogador6 = new javax.swing.JLabel();
        lblJogador3 = new javax.swing.JLabel();
        lblStatusjogador7 = new javax.swing.JLabel();
        lblJogador4 = new javax.swing.JLabel();
        lblStatusjogador8 = new javax.swing.JLabel();
        lblJogador5 = new javax.swing.JLabel();
        lblStatusjogador2 = new javax.swing.JLabel();
        lblJogador6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblJogador7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblJogador8 = new javax.swing.JLabel();
        btnIniciarPartida = new javax.swing.JButton();

        jButton3.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStatusjogador1.setText("Offline");

        lblStatusjogador3.setText("Offline");

        lblJogador1.setText("Vazio");

        lblStatusjogador4.setText("Offline");

        lblStatusjogador5.setText("Offline");

        lblJogador2.setText("Vazio");

        lblStatusjogador6.setText("Offline");

        lblJogador3.setText("Vazio");

        lblStatusjogador7.setText("Offline");

        lblJogador4.setText("Vazio");

        lblStatusjogador8.setText("Offline");

        lblJogador5.setText("Vazio");

        lblStatusjogador2.setText("Offline");

        lblJogador6.setText("Vazio");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Jogadores");

        lblJogador7.setText("Vazio");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("Status");

        lblJogador8.setText("Vazio");

        btnIniciarPartida.setText("Iniciar Partida");
        btnIniciarPartida.setActionCommand("btnIniciaPartida");
        btnIniciarPartida.setName("btnIniciarPartida"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIniciarPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJogador8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblStatusjogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStatusjogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStatusjogador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStatusjogador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStatusjogador5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStatusjogador6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStatusjogador7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStatusjogador8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJogador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJogador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJogador3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJogador4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJogador5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJogador6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJogador7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJogador8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatusjogador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusjogador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusjogador3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusjogador4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusjogador5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusjogador6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusjogador7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusjogador8)))
                .addGap(36, 36, 36)
                .addComponent(btnIniciarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        lblStatusjogador1.getAccessibleContext().setAccessibleName("lblJogador1Status");
        lblStatusjogador3.getAccessibleContext().setAccessibleName("lblJogador3Status");
        lblJogador1.getAccessibleContext().setAccessibleName("lblJogador1");
        lblStatusjogador4.getAccessibleContext().setAccessibleName("lblJogador4Status");
        lblStatusjogador5.getAccessibleContext().setAccessibleName("lblJogador5Status");
        lblJogador2.getAccessibleContext().setAccessibleName("lblJogador2");
        lblStatusjogador6.getAccessibleContext().setAccessibleName("lblJogador6Status");
        lblJogador3.getAccessibleContext().setAccessibleName("lblJogador3");
        lblStatusjogador7.getAccessibleContext().setAccessibleName("lblJogador5Status");
        lblJogador4.getAccessibleContext().setAccessibleName("lblJogador4");
        lblStatusjogador8.getAccessibleContext().setAccessibleName("lblJogador8Status");
        lblJogador5.getAccessibleContext().setAccessibleName("lblJogador5");
        lblStatusjogador2.getAccessibleContext().setAccessibleName("lblJogador2Status");
        lblStatusjogador2.getAccessibleContext().setAccessibleDescription("");
        lblJogador6.getAccessibleContext().setAccessibleName("lblJogador6");
        jLabel17.getAccessibleContext().setAccessibleName("lblJogadores");
        lblJogador7.getAccessibleContext().setAccessibleName("lblJogador7");
        lblJogador8.getAccessibleContext().setAccessibleName("lblJogador8");
        btnIniciarPartida.getAccessibleContext().setAccessibleName("btnIniciaPArtida");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrePartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel lblJogador1;
    private javax.swing.JLabel lblJogador2;
    private javax.swing.JLabel lblJogador3;
    private javax.swing.JLabel lblJogador4;
    private javax.swing.JLabel lblJogador5;
    private javax.swing.JLabel lblJogador6;
    private javax.swing.JLabel lblJogador7;
    private javax.swing.JLabel lblJogador8;
    private javax.swing.JLabel lblStatusjogador1;
    private javax.swing.JLabel lblStatusjogador2;
    private javax.swing.JLabel lblStatusjogador3;
    private javax.swing.JLabel lblStatusjogador4;
    private javax.swing.JLabel lblStatusjogador5;
    private javax.swing.JLabel lblStatusjogador6;
    private javax.swing.JLabel lblStatusjogador7;
    private javax.swing.JLabel lblStatusjogador8;
    // End of variables declaration//GEN-END:variables
}
